# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 235a4f2fbe8dac717387df8ce02cd42969f2ffea05522a2ea29d5e6b65b75bce9ea28e42f7f78aa62f1b4e7b89601eb2e238bbc5723b4eaa6b7c160ef2e7a135

test:
  secret_key_base: 312c043767bf2b13939e09d561e0b5b26221aed552294ee4e6fbad2162639d9eb27eef869db7264dd89e0b00574b9ed5a1c6fc4da90ef4698ae711b9e5d5e441

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
